import { GeistSans } from "geist/font/sans";
import "./globals.css";
import SideNavbar from "./ui/SideNavbar";
import TopBar from "./ui/TopBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-[#fafafa]`}>
        <div className="selection:bg-[#DAF996]">
          <SideNavbar />
          {/* <Sidebar /> */}
        </div>
        <div className="selection:bg-[#DAF996] lg:ml-72">
          <TopBar />
          {children}
        </div>
      </body>
    </html>
  );
}
