import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "./ui/SideNavbar";
import TopBar from "./ui/TopBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#fafafa]`}>
        <div className='selection:bg-[#DAF996]'>
          <SideNavbar />
          {/* <Sidebar /> */}

        </div>
        <div className="lg:ml-72 selection:bg-[#DAF996]  ">
          <TopBar />
          {children}
        </div>
      </body>
    </html>
  );
}
