const cards = [
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        date: "16th April 2024",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
]

export default cards;