const cards = [
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam pariatur omnis debitis quo odit? Repellat qui odio quos, eligendi vitae fugit sint expedita magnam inventore veritatis ipsam totam sequi ab accusamus earum deserunt laborum ullam!",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        status: "Highly Active",
        role: "Design",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
]

export default cards;