const cards = [
    {
        key: 1,
        status: "Highly Active",
        title: "2025 Corporate & Investment Bank Investment Banking Sophomore Summer Analyst Program - Latin America Advisory",
        description: "Charlotte, NC • Chandler, AZ • Roanoke, VA • San Antonio, TX • West Des Moines, IA",
        author: "JPMorgan Chase & Co.",
    },
    {
        key: 2,
        status: "Highly Active",
        title: "Career Development Program: Fraud & Claims Operations Associate",
        description: "Charlotte, NC • Chandler, AZ • Roanoke, VA • San Antonio, TX • West Des Moines, IA",
        author: "Khatab wedaa",
    },
    {
        key: 3,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 4,
        status: "Highly Active",
        title: "Career Development Program: Fraud & Claims Operations Associate",
        description: "Charlotte, NC • Chandler, AZ • Roanoke, VA • San Antonio, TX • West Des Moines, IA",
        author: "Khatab wedaa",
    },
    {
        key: 5,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 6,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 7,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Aditya Pandey",
    },
    {
        key: 8,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 9,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 10,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 11,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 12,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 13,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 14,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 15,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 16,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 17,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    },
    {
        key: 18,
        status: "Highly Active",
        title: "Accessibility tools for designers and developers",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempora expedita dicta totam aspernatur doloremque.",
        author: "Khatab wedaa",
    }
]

export default cards;